[project]
name = "openpoketcg-scraper"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.12",
    "pre-commit>=4.2.0",
]
