name: Rebuild Card Data (Weekly)

on:
  schedule:
    - cron: '0 2 * * 1'  # Runs at 02:00 UTC every Monday
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true
                cache-dependency-glob: "uv.lock"
                version: "0.7.9"

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: '.python-version'

            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run Rebuild Script
              env:
                SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_PORT: ${{ secrets.DB_PORT }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASS: ${{ secrets.DB_PASS }}

              run: PYTHONPATH=. uv run scripts/rebuild_db.py
